import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#FFFFFF", padding: 16 },
  header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 16, marginTop: 50 },
  logo: { fontSize: 24, fontWeight: "bold" },
  headerIcons: { flexDirection: "row", alignItems: "center", gap: 10 },
  icon: { marginLeft: 8, color: "#7D7D7D" },
  balanceContainer: { backgroundColor: "#F2C94C", borderRadius: 10, padding: 16, marginBottom: 16 },
  balanceHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  balanceTitle: { fontSize: 16, color: "#333333" },
  balanceValue: { fontSize: 32, fontWeight: "bold", color: "#333333", marginVertical: 8 },
  balanceActions: { flexDirection: "row", justifyContent: "space-between", width: "100%" },
  actionButton: { flexDirection: "row", alignItems: "center", backgroundColor: "#FFFFFF", padding: 13, borderRadius: 10, elevation: 3, width: "48%", justifyContent: "center", opacity: 0.8 },
  actionText: { marginLeft: 8, fontSize: 14, color: "#333333" },
  navigation: { flexDirection: "row", justifyContent: "space-between", marginBottom: 16 },
  navItem: { alignItems: "center" },
  navIcon: { justifyContent: "center", alignItems: "center", borderRadius: 50, width: 58, height: 58 },
  navText: { marginTop: 8, fontSize: 12, color: "#333333" },
  section: { marginBottom: 24 },
  sectionTitle: { fontSize: 18, fontWeight: "bold", color: "#333333", marginBottom: 8 },
  goalBox: { backgroundColor: "#F5F5F5", borderRadius: 10, padding: 16, marginBottom: 8 },
  goal: { flexDirection: "row", alignItems: "center", marginBottom: 8 },
  goalIcon: { justifyContent: "center", alignItems: "center", backgroundColor: "#E0E7FF", borderRadius: 50, width: 38, height: 38, marginRight: 10 },
  goalTitle: { fontSize: 14, fontWeight: "bold", color: "#333333" },
  goalSubtitle: { fontSize: 12, color: "#7D7D7D" },
  progressBar: { height: 8, backgroundColor: "#E0E0E0", borderRadius: 4 },
  progress: { height: "100%", backgroundColor: "#4CAF50", borderRadius: 4 },
  transactionHeader: { flexDirection: "row", justifyContent: "space-between", marginBottom: 10 },
  transactionBox: { flexDirection: "row", alignItems: "center", backgroundColor: "#F5F5F5", padding: 16, borderRadius: 10, marginBottom: 8, elevation: 3 },
  transactionIcon: { justifyContent: "center", alignItems: "center", backgroundColor: "#E0E7FF", borderRadius: 50, width: 38, height: 38, marginRight: 10 },
  transactionDetails: { flex: 1, flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  transactionTitle: { fontSize: 14, color: "#333333" },
  transactionAmount: { fontSize: 14, fontWeight: "bold" },
  emptyText: {
    fontSize: 14,
    color: "#7F8C8D",
    textAlign: "center",
    marginTop: 10,
  },
});